version: '3.0'



services:

   db:
     
     build:

      context: .

      dockerfile: dockerfile
     
     #image: hshar/mysql:5.6
     
     container_name: db

     volumes:

       - db_data:/var/lib/mysql

     restart: always

     environment:

       MYSQL_ROOT_PASSWORD: intelli

       #MYSQL_DATABASE: docker



   wordpress:

     depends_on:

       - db

     image: hshar/webapp:latest
      
     container_name: webapp
     
     ports:

       - "8000:80"

     restart: always

volumes:

    db_data:
